### ISSUE TITLE
System.Html.History doesn't transpile correctly

### ISSUE THREAD

**Issue by ZacharyJ** [DerivcoIpswich/dsharp#59]
Should transpile to window.history.scrollRestoration but transpiles to History.ScrollRestoration which is not defined

**Comment by adrianodfo** [comment]
I've changed the implementation to 

[ScriptField]
public string ScrollRestoration { get; set; }

It worked for Chrome and Firefox.

**Comment by fred-perkins** [comment]
Bug fix has been merged into develop. Closing #78
