### ISSUE TITLE
There are empty month names in Culture.js

### ISSUE THREAD

**Issue by charlisi** [DerivcoIpswich/dsharp#64]
Is there a reason for these empty string in month name arrays in Culture.js? Drop them if not please.

**Comment by fred-perkins** [comment]
Oh yeh I see them. Not sure why they exist. The culture data should match the neutral culture from CSharp. Not sure CSharp actually outputs though!

**Comment by fred-perkins** [comment]
After checking what .Net does I can confirm that this is expected behaviour.
